version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/wuqianma2024/books_recommend:latest
    ports:
      - "8501:8501"
    command: streamlit run app/app.py
